#!/bin/sh
#
# Edit to suit save to .xinitrc, also link ln -s .xinitrc .xsession
#

xrdb -merge ~/.Xresources
xkbset m
xkbset exp "=mousekeys"
xmodmap ~/.Xmodmap

export XDG_CURRENT_DESKTOP=dwm
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_ENABLE_HIGHDPI_SCALING=1

if [ -d "$xinitdir"/xinitrc.d ] ; then
	for f in "$xinitdir/xinitrc.d"/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

#dex --autostart --environment dwm

# start battery warning
~/bin/i3-battery-popup -t 1m &

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
xset dpms 600 s off
xss-lock -l -- i3lock -f -c 285577 -e -n &

slstatus &

sxhkd &

nm-applet &

~/bin/pcloud &

# start this stuff delayed, first start dwm
(
sleep 2

ibus-daemon -r -x -R -d

# compositor
picom --no-fading-openclose -b --backend xrender

#set background
~/.fehbg &
) &

#exec ssh-agent dwm
rm -f ~/.dwm/reallyquit
while :; do
	ssh-agent dwm
	if [ -e ~/.dwm/reallyquit ]; then exit 0 ; fi
done
